# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


url: https://sampath.dev/
baseurl: /
title: Sai Sampath Kumar Balivada
author: Sampath Balivada
description: Personal blog
avatar: profile.png
email: balivadask2000@gmail.com
github: sampathbalivada # username
twitter: sampathbalivada
linkedin: sampathbalivada
stackoverflow: users/10150607/sampath-balivada
#Comment out if you don't want disqus
disqus: sampathdev
google_analytics: UA-147475582-1


# needed for travis-ci build
exclude: [vendor]
